### ISSUE TITLE
Wish list for version 1.0.0

### ISSUE THREAD

**Issue by ZBlocker655** [x-cubed/event-store-client#11]
I'm curious, @x-cubed.  Is there a wishlist for version 1.0.0?  Can you post it?  My team is beginning to build Node services using this client, and if we have an opportunity to further contribute (and if we find time to do so) we can continue to help.

**Comment by x-cubed** [comment]
Hi Zach,

There's no wishlist for version 1.0.0. I was originally working on a Node.js project that needed to tie into Event Store, and seeing as there wasn't an existing client around, we decided to write our own. The general aim was to implement a library that followed the .Net client API as closely as possible, albeit in JS. The original project I was working on has shipped, and seems to be working well, but as I'm no longer working on it, I personally have no current need for this library any more.

There seems to have been a decent number of functionality added to Event Store in the meantime, but I haven't been keeping up with the changes myself. I reached out to the Event Store team a while back, to see if they would be interested in taking this module on as an official client, but I haven't heard back.

In the meantime, I'm happy to review and merge any changes that you need.

Thanks for your contributions so far.
