### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by akoenig** [x-cubed/event-store-client#26]
Awesome library. Thanks for building it. We are using TypeScript within our projects and identified that you are also providing a type definition file. Cool! Unfortunately there is a discrepancy between the `package.json` which lives in the `master` branch and the one that gets distributed by npm. The one in the `master` references the type definition file correctly and the actual package on npm does not has a `types` attribute at all. Would it be possible to publish a patch version `0.0.11` with the correct `package.json` in it?

**Edit:** It also seems that the typings within the `master` are old. Would it also be possible to update them?

**Comment by x-cubed** [comment]
Yeah, I've been meaning to publish a new version for a while. I'll do that in the next couple of days.

**Comment by x-cubed** [comment]
Version 0.0.11 has been published with the types property defined (#25)
https://www.npmjs.com/package/event-store-client

What are you referring to when you talk about "old" typings? They should all be up-to-date.

**Comment by akoenig** [comment]
Awesome. Thanks @x-cubed 

> What are you referring to when you talk about "old" typings? They should all be up-to-date.

Last time I checked, I received some function signature problems. Will check back when facing them again.

**Comment by sledorze** [comment]
@akoenig should be closed I guess..
