### ISSUE TITLE
How to handle connection errors?

### ISSUE THREAD

**Issue by majnu-campact** [x-cubed/event-store-client#27]
Hi, we love and use your library! One thing I can't figure out though is how to detect a connection error. 
We use `writeEvents` and wait for the success-callback. If the event store went down for some reason I can see a log output of the connection error, but I don't see a way to catch and react to it in my code. Do you have a hint for me?

**Comment by x-cubed** [comment]
When creating the Connection object, you can define a handler in the options.onError property to handle the socket onError event.

See [connection.js](https://github.com/x-cubed/event-store-client/blob/master/lib/connection.js#L56)

**Comment by majnu-campact** [comment]
@x-cubed  Thanks! I didn't find it in the typescript definitions, therefore I was a little confused. Works fine now!
