### ISSUE TITLE
Catchup Subscription

### ISSUE THREAD

**Issue by PaulGrimshaw** [x-cubed/event-store-client#3]
How does one start a catchup subscription through this client?

**Comment by x-cubed** [comment]
That's not currently supported, but you can achieve the same thing by subscribing to a stream, then reading the existing events from the stream up to the point where your subscription started.

Feel free to submit a pull request that implements that functionality.

**Comment by x-cubed** [comment]
This functionality has been merged in thanks to @ZBlocker655's pull request.
