### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by mlouage** [x-cubed/event-store-client#30]
Hello

Does this client support an SSL connection to Eventstore?

Thanks
Maarten

**Comment by x-cubed** [comment]
No, the purpose of this library is to implement the binary Protocol Buffers protocol used by Event Store, and that binary protocol is not encrypted. The binary protocol is more efficient in terms of network use and allows the ability to subscribe to event notifications.

If you want to use the Event Store API that is available over HTTP or HTTPS, you don't need this library, you can just invoke the API directly using normal web requests.
