### ISSUE TITLE
typedefinition bug

### ISSUE THREAD

**Issue by ghost** [x-cubed/event-store-client#38]
In the type definition:
subscribeToStreamFrom(streamId: string, fromEventNumber: number, ...)

Should be:
subscribeToStreamFrom(streamId: string, fromEventNumber: number **| null**, ...)

It is missing the `| null`, for the `fromEventNumber` parameter.  Without it, you cannot read from the beginning of the stream.

**Comment by x-cubed** [comment]
Thanks for pointing that out, I've pushed a commit to resolve it
