### ISSUE TITLE
StoredEvent data and others received as Buffer

### ISSUE THREAD

**Issue by mariobittencourt** [x-cubed/event-store-client#39]
Hi,  I am using this library to interface with the event store 5.0.8.

I am able to write to the streams and by checking in the web interface I can see the contents correctly, such as the event type and the data.

But when I subscribe, I see that some fields are returned as Buffer.  Example of a console.log of one event retrieved shows
```
{
  streamId: '$ce-mystream',
  eventNumber: 54,
  eventId: 'bad6ce85-edff-4c13-a6fa-63c7f755257a',
  eventType: '$>',
  isJson: false,
  created: 2020-05-10T19:40:23.166Z,
  data: <Buffer ...
```

I could not find how to have access to the original value

**Comment by x-cubed** [comment]
Hi Mario,

The Buffer API is described at: https://nodejs.org/api/buffer.html

If the data you're dealing with is text, you can call [toString()](https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end) on the Buffer object to decode the bytes from UTF-8 to a string. 

If you're dealing with binary data, you can use the [values()](https://nodejs.org/api/buffer.html#buffer_buf_values) function to get an iterator that returns each byte, or you can use the [.read*()](https://nodejs.org/api/buffer.html#buffer_buf_readint32le_offset) methods to read the bytes as integers, etc.

**Comment by mariobittencourt** [comment]
Hi, thanks for the quick reply.  I am reading from a  stream created from a standard category projection, so I have individual streams called something-**** so it creates a $ce-something.

the eventType appears as '$>' and the data, after toString shows something like `2@something-45c343fc-4051-468c-baf3-eefe052595be` which is the order and stream name of the origin event.

I wonder if I am doing something wrong on this case. In this case, is there a way to navigate to the actual event content directly ?

**Comment by mariobittencourt** [comment]
Hi, @x-cubed nevermind. the settings resolve link tos was set to false.  By setting to true I am receiving the original event as expected.
