### ISSUE TITLE
Accessing linked event information

### ISSUE THREAD

**Issue by ZBlocker655** [x-cubed/event-store-client#5]
Noticed that when consuming events from a stream built by a projection, with the "resolveLinkTos" option set to true, the deserializer appears to ignore what's in the link: { } structure entirely.  This means that I can't get at the event numbers from the projection stream, just the ones from the stream that the link-resolved event comes from.  So there's no way to track sequential event numbers in a projection stream if I also want the linked events resolved. 

Relevant code: lib/connection.js - unpackResolvedEvent(resolvedEvent) -> return unpackEventRecord(resolvedEvent.event);

See Google Groups issue I raised: https://groups.google.com/forum/#!topic/event-store/MIsb87kjvzE

**Comment by x-cubed** [comment]
Merged and released as v0.0.6
